// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PretoriaUniversity.Data;

namespace PretoriaUniversity.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20210220192336_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("PretoriaUniversity.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("GendacProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "CategoryA",
                            Name = "Stove",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "CategoryB",
                            Name = "Fridge",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "CategoryA",
                            Name = "Stove",
                            Price = 29.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
